//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance.widget;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class View_AdultBalanceNoFatData_
    extends View_AdultBalanceNoFatData
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public View_AdultBalanceNoFatData_(Context context) {
        super(context);
        init_();
    }

    public View_AdultBalanceNoFatData_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static View_AdultBalanceNoFatData build(Context context) {
        View_AdultBalanceNoFatData_ instance = new View_AdultBalanceNoFatData_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_adultbalancenofatdata, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static View_AdultBalanceNoFatData build(Context context, AttributeSet attrs) {
        View_AdultBalanceNoFatData_ instance = new View_AdultBalanceNoFatData_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnSuggest = ((Button) hasViews.findViewById(id.btnSuggest));
        tvTop_2 = ((TextView) hasViews.findViewById(id.tvTop_2));
        imgTopRightBottom = ((ImageView) hasViews.findViewById(id.imgTopRightBottom));
        tvTop_1 = ((TextView) hasViews.findViewById(id.tvTop_1));
        tvBottom_2 = ((TextView) hasViews.findViewById(id.tvBottom_2));
        tvBottom_1 = ((TextView) hasViews.findViewById(id.tvBottom_1));
        rlRoot = ((RelativeLayout) hasViews.findViewById(id.rlRoot));
        tvTopRightTop = ((TextView) hasViews.findViewById(id.tvTopRightTop));
        btnRank = ((Button) hasViews.findViewById(id.btnRank));
        tvBottomRight = ((TextView) hasViews.findViewById(id.tvBottomRight));
        tvTopRightBottom = ((TextView) hasViews.findViewById(id.tvTopRightBottom));
        imgTopRightTop = ((ImageView) hasViews.findViewById(id.imgTopRightTop));
        tvMsg = ((TextView) hasViews.findViewById(id.tvMsg));
        if (btnSuggest!= null) {
            btnSuggest.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_AdultBalanceNoFatData_.this.showSuggest();
                }

            }
            );
        }
        if (btnRank!= null) {
            btnRank.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_AdultBalanceNoFatData_.this.showRank();
                }

            }
            );
        }
        init();
    }

}
