//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance.widget;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class View_Item_BalanceData_
    extends View_Item_BalanceData
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public View_Item_BalanceData_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public View_Item_BalanceData_(Context context, ScrollViewExtend scroll, View_ShowBalanceData parentView) {
        super(context, scroll, parentView);
        init_();
    }

    public static View_Item_BalanceData build(Context context, AttributeSet attrs) {
        View_Item_BalanceData_ instance = new View_Item_BalanceData_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_item_balancedata, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static View_Item_BalanceData build(Context context, ScrollViewExtend scroll, View_ShowBalanceData parentView) {
        View_Item_BalanceData_ instance = new View_Item_BalanceData_(context, scroll, parentView);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnDelete = ((Button) hasViews.findViewById(id.btnDelete));
        imgHeadImage = ((ImageView) hasViews.findViewById(id.imgHeadImage));
        tvDate = ((TextView) hasViews.findViewById(id.tvDate));
        tvDay = ((TextView) hasViews.findViewById(id.tvDay));
        lockableHorizontalScrollView1 = ((LockableHorizontalScrollView) hasViews.findViewById(id.lockableHorizontalScrollView1));
        imgLine = ((ImageView) hasViews.findViewById(id.imgLine));
        llFont = ((LinearLayout) hasViews.findViewById(id.llFont));
        tvBMI = ((TextView) hasViews.findViewById(id.tvBMI));
        tvWeight = ((TextView) hasViews.findViewById(id.tvWeight));
        llBack = ((LinearLayout) hasViews.findViewById(id.llBack));
        tvTime = ((TextView) hasViews.findViewById(id.tvTime));
        if (btnDelete!= null) {
            btnDelete.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_Item_BalanceData_.this.delete();
                }

            }
            );
        }
        init();
    }

}
