//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance.widget;

import android.content.Context;
import android.util.AttributeSet;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.ViewFlipper;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import com.vc.cloudbalance.model.MemberMDL;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class View_ShowBalanceData_
    extends View_ShowBalanceData
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public View_ShowBalanceData_(Context context, MemberMDL mdl) {
        super(context, mdl);
        init_();
    }

    public View_ShowBalanceData_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static View_ShowBalanceData build(Context context, MemberMDL mdl) {
        View_ShowBalanceData_ instance = new View_ShowBalanceData_(context, mdl);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_showbalancedata, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static View_ShowBalanceData build(Context context, AttributeSet attrs) {
        View_ShowBalanceData_ instance = new View_ShowBalanceData_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        viewFlipper = ((ViewFlipper) hasViews.findViewById(id.viewFlipper));
        rb1 = ((RadioButton) hasViews.findViewById(id.rb1));
        rb2 = ((RadioButton) hasViews.findViewById(id.rb2));
        rbg1 = ((RadioGroup) hasViews.findViewById(id.rbg1));
        init();
    }

}
