//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance.widget;

import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import de.hdodenhof.circleimageview.CircleImageView;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class View_Item_Member_
    extends View_Item_Member
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public View_Item_Member_(Context context) {
        super(context);
        init_();
    }

    public View_Item_Member_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static View_Item_Member build(Context context) {
        View_Item_Member_ instance = new View_Item_Member_(context);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_item_member, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static View_Item_Member build(Context context, AttributeSet attrs) {
        View_Item_Member_ instance = new View_Item_Member_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnData = ((Button) hasViews.findViewById(id.btnData));
        circleImageView = ((CircleImageView) hasViews.findViewById(id.circleImageView));
        llFont = ((LinearLayout) hasViews.findViewById(id.llFont));
        tvName = ((TextView) hasViews.findViewById(id.tvName));
        llBack = ((LinearLayout) hasViews.findViewById(id.llBack));
        btnEdit = ((Button) hasViews.findViewById(id.btnEdit));
        imgHeadImage = ((ImageView) hasViews.findViewById(id.imgHeadImage));
        imgLine = ((ImageView) hasViews.findViewById(id.imgLine));
        lockableHorizontalScrollView1 = ((LockableHorizontalScrollView) hasViews.findViewById(id.lockableHorizontalScrollView1));
        if (btnData!= null) {
            btnData.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_Item_Member_.this.showDataActivity();
                }

            }
            );
        }
        if (btnEdit!= null) {
            btnEdit.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_Item_Member_.this.showMemberInfoActivity();
                }

            }
            );
        }
        init();
    }

}
