//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance.widget;

import android.content.Context;
import android.support.v4.view.ViewPager;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.RadioButton;
import android.widget.RelativeLayout;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import com.vc.cloudbalance.model.MemberMDL;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class View_BalanceDataChart_
    extends View_BalanceDataChart
    implements HasViews, OnViewChangedListener
{

    private boolean alreadyInflated_ = false;
    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    public View_BalanceDataChart_(Context context, MemberMDL member) {
        super(context, member);
        init_();
    }

    public View_BalanceDataChart_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public static View_BalanceDataChart build(Context context, MemberMDL member) {
        View_BalanceDataChart_ instance = new View_BalanceDataChart_(context, member);
        instance.onFinishInflate();
        return instance;
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!alreadyInflated_) {
            alreadyInflated_ = true;
            inflate(getContext(), layout.view_balancedatachart, this);
            onViewChangedNotifier_.notifyViewChanged(this);
        }
        super.onFinishInflate();
    }

    private void init_() {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    public static View_BalanceDataChart build(Context context, AttributeSet attrs) {
        View_BalanceDataChart_ instance = new View_BalanceDataChart_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        rbType1 = ((RadioButton) hasViews.findViewById(id.rbType1));
        rbDate4 = ((RadioButton) hasViews.findViewById(id.rbDate4));
        rbType5 = ((RadioButton) hasViews.findViewById(id.rbType5));
        viewpager = ((ViewPager) hasViews.findViewById(id.viewpager));
        rbType2 = ((RadioButton) hasViews.findViewById(id.rbType2));
        llPanel = ((RelativeLayout) hasViews.findViewById(id.llPanel));
        rbDate2 = ((RadioButton) hasViews.findViewById(id.rbDate2));
        btnNext = ((Button) hasViews.findViewById(id.btnNext));
        rbType3 = ((RadioButton) hasViews.findViewById(id.rbType3));
        rbType6 = ((RadioButton) hasViews.findViewById(id.rbType6));
        btnPre = ((Button) hasViews.findViewById(id.btnPre));
        rbType4 = ((RadioButton) hasViews.findViewById(id.rbType4));
        rbDate3 = ((RadioButton) hasViews.findViewById(id.rbDate3));
        rbDate1 = ((RadioButton) hasViews.findViewById(id.rbDate1));
        if (btnPre!= null) {
            btnPre.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_BalanceDataChart_.this.pre();
                }

            }
            );
        }
        if (btnNext!= null) {
            btnNext.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    View_BalanceDataChart_.this.next();
                }

            }
            );
        }
        init();
    }

}
