//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.1.
//


package com.vc.cloudbalance;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.view.Window;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.vc.cloudbalance.R.id;
import com.vc.cloudbalance.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class AccoutActivity_
    extends AccoutActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.activity_account);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static AccoutActivity_.IntentBuilder_ intent(Context context) {
        return new AccoutActivity_.IntentBuilder_(context);
    }

    public static AccoutActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new AccoutActivity_.IntentBuilder_(fragment);
    }

    public static AccoutActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new AccoutActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        btnBack = ((Button) hasViews.findViewById(id.btnBack));
        tvTitle = ((TextView) hasViews.findViewById(id.tvTitle));
        btnQQBind = ((Button) hasViews.findViewById(id.btnQQBind));
        tvSysUserName = ((TextView) hasViews.findViewById(id.tvSysUserName));
        imgWB = ((ImageView) hasViews.findViewById(id.imgWB));
        imgQQ = ((ImageView) hasViews.findViewById(id.imgQQ));
        btnSysReg = ((Button) hasViews.findViewById(id.btnSysReg));
        btnWBBind = ((Button) hasViews.findViewById(id.btnWBBind));
        btnWBUnBind = ((Button) hasViews.findViewById(id.btnWBUnBind));
        imgSys = ((ImageView) hasViews.findViewById(id.imgSys));
        btnQQUnBind = ((Button) hasViews.findViewById(id.btnQQUnBind));
        if (btnBack!= null) {
            btnBack.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.goBack();
                }

            }
            );
        }
        if (btnWBBind!= null) {
            btnWBBind.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.WeiBoLogin();
                }

            }
            );
        }
        if (btnQQBind!= null) {
            btnQQBind.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.QQLogin();
                }

            }
            );
        }
        {
            View view = hasViews.findViewById(id.btnLogOut);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AccoutActivity_.this.Logout();
                    }

                }
                );
            }
        }
        if (btnWBUnBind!= null) {
            btnWBUnBind.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.WeiBoUnBind();
                }

            }
            );
        }
        if (btnSysReg!= null) {
            btnSysReg.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.Reg();
                }

            }
            );
        }
        if (btnQQUnBind!= null) {
            btnQQUnBind.setOnClickListener(new OnClickListener() {


                @Override
                public void onClick(View view) {
                    AccoutActivity_.this.QQUnBind();
                }

            }
            );
        }
        InitBase();
        init();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<AccoutActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, AccoutActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), AccoutActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), AccoutActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
